name: Shell commands
on: [push]
jobs:
  run-shell-command:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04]
    steps:
      - name: echo a string
        run: echo "Hello world"
      - name: show python version
        run: python3 -V
      - name: create a file
        run: touch my_file_with_workflow.py
      - name: list files
        run: ls -l
